/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

apply plugin: 'java'
apply plugin: 'war'

// https://www.apache.org/legal/resolved.html#category-a
dependencies {
    implementation project(":tcbot-engine")
    implementation project(':migrator')
    runtimeOnly project(":tcbot-app-guice")

    implementation "org.apache.ignite:ignite-core:$ignVer"
    implementation "org.apache.ignite:ignite-slf4j:$ignVer"
    implementation "org.apache.ignite:ignite-direct-io:$ignVer"

    implementation 'javax.inject:javax.inject:1'

    implementation "com.google.code.gson:gson:$gsonVer"

    implementation "org.slf4j:slf4j-api:$slf4jVer"
    implementation "org.slf4j:jul-to-slf4j:$slf4jVer"

    implementation "ch.qos.logback:logback-core:$logbackVer"
    implementation "ch.qos.logback:logback-classic:$logbackVer"

    implementation "org.eclipse.jetty:jetty-util:$jettyVer"
    implementation "org.eclipse.jetty:jetty-server:$jettyVer"
    implementation "org.eclipse.jetty.ee8:jetty-ee8-webapp:$jettyVer"

    implementation "org.glassfish.jersey.containers:jersey-container-servlet-core:$jerseyVer"

    implementation "org.glassfish.jersey.core:jersey-client:$jerseyVer"
    //
    implementation "org.glassfish.jersey.inject:jersey-hk2:$jerseyVer"

    implementation "org.glassfish.jersey.media:jersey-media-json-jackson:$jerseyVer"
    implementation "org.glassfish.jersey.media:jersey-media-multipart:$jerseyVer"

    testImplementation "junit:junit:$junitVer"
    testImplementation "org.mockito:mockito-core:$mockitoVer"
    testImplementation project(":tcbot-app-guice")
    testImplementation "com.google.inject:guice:$guiceVer"
}

processResources {
    from(sourceSets.test.resources.srcDirs) {
        include "**/*.json"
    }
}

war {
    into('WEB-INF/classes/static') {
        from 'src/main/webapp'
        exclude 'WEB-INF/**'
    }
}

test {
    // set JVM arguments for the test JVM(s)
    jvmArgs igniteJava17JvmArgs
}
